# Generated by Django 3.0.5 on 2020-12-01 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of regular plan')),
                ('tar_included', models.BooleanField(default=False, verbose_name='Tax included?')),
                ('subscription', models.FloatField(default=0.0, verbose_name='it’s the monthly subscription for the user')),
                ('cycle', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly')], max_length=1, verbose_name='if it’s daily or weekly')),
                ('type', models.CharField(choices=[('TS', 'simple'), ('TB', 'bi-time'), ('TT', 'tri-time')], max_length=2, verbose_name='if it’s daily or weekly')),
                ('offer_iva', models.BooleanField(default=False, verbose_name='Tax included?')),
                ('off_peak_price', models.FloatField(default=0.0, verbose_name='off peak price')),
                ('peak_price', models.FloatField(default=0.0, verbose_name='peak price')),
                ('unit', models.CharField(choices=[('KH', 'KWH'), ('MN', 'MIN')], max_length=2, verbose_name='kwh or min')),
                ('valid', models.BooleanField(default=True, verbose_name='Is valid?')),
                ('publish', models.BooleanField(default=False, verbose_name='Published?')),
                ('vat', models.IntegerField(default=1, verbose_name='can be from 1 to 100')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.Owner')),
            ],
        ),
    ]
